type Flight = {
  id: number;
  departureTimeOutbound: string;
  arrivalTimeOutbound: string;
  departureAirportOutbound: string;
  arrivalAirportOutbound: string;
  airlineOutbound: string;
  flightNumberOutbound: string;
  departureTimeReturn: string;
  arrivalTimeReturn: string;
  departureAirportReturn: string;
  arrivalAirportReturn: string;
  airlineReturn: string;
  flightNumberReturn: string;
  durationOutbound: number;
  durationReturn: number;
  price: number;
  selfTransfer?: boolean;
};

export const flightsData: Flight[] = [
  {
    id: 1,
    departureTimeOutbound: "07:00",
    arrivalTimeOutbound: "08:45",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "Airblue",
    flightNumberOutbound: "PA-201",
    departureTimeReturn: "11:00",
    arrivalTimeReturn: "12:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "Airblue",
    flightNumberReturn: "PA-202",
    durationOutbound: 105,
    durationReturn: 60,
    price: 37017,
  },
  {
    id: 2,
    departureTimeOutbound: "06:00",
    arrivalTimeOutbound: "07:30",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "PIA",
    flightNumberOutbound: "PK-601",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "13:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-602",
    durationOutbound: 90,
    durationReturn: 60,
    price: 30785,
  },
  {
    id: 3,
    departureTimeOutbound: "09:55",
    arrivalTimeOutbound: "12:00",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "Airblue",
    flightNumberOutbound: "PA-205",
    departureTimeReturn: "11:00",
    arrivalTimeReturn: "12:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "Airblue",
    flightNumberReturn: "PA-206",
    durationOutbound: 125,
    durationReturn: 60,
    price: 30785,
  },
  {
    id: 4,
    departureTimeOutbound: "06:00",
    arrivalTimeOutbound: "07:30",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "PIA",
    flightNumberOutbound: "PK-601",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "13:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-602",
    durationOutbound: 90,
    durationReturn: 60,
    price: 39281,
  },
  {
    id: 5,
    departureTimeOutbound: "18:00",
    arrivalTimeOutbound: "19:00",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "LHE",
    airlineOutbound: "PIA",
    flightNumberOutbound: "PK-307",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "13:00",
    departureAirportReturn: "LHE",
    arrivalAirportReturn: "KDU",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-653",
    durationOutbound: 60,
    durationReturn: 60,
    price: 87844,
    selfTransfer: true,
  },
  {
    id: 6,
    departureTimeOutbound: "12:30",
    arrivalTimeOutbound: "08:15",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "PIA",
    flightNumberOutbound: "PK-605",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "12:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-606",
    durationOutbound: 12 * 60 + 45,
    durationReturn: 0,
    price: 75401,
  },
  {
    id: 7,
    departureTimeOutbound: "10:00",
    arrivalTimeOutbound: "08:15",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "PIA",
    flightNumberOutbound: "PK-603",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "12:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-604",
    durationOutbound: 22 * 60 + 15,
    durationReturn: 0,
    price: 75404,
    selfTransfer: true,
  },
  {
    id: 8,
    departureTimeOutbound: "20:00",
    arrivalTimeOutbound: "08:15",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "PIA",
    flightNumberOutbound: "PK-607",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "12:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-608",
    durationOutbound: 12 * 60 + 15,
    durationReturn: 0,
    price: 72290,
    selfTransfer: true,
  },
  {
    id: 9,
    departureTimeOutbound: "23:00",
    arrivalTimeOutbound: "08:15",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "Emirates via PIA",
    flightNumberOutbound: "EK-380 / PK-609",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "12:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-610",
    durationOutbound: 9 * 60 + 15,
    durationReturn: 0,
    price: 70371,
  },
  {
    id: 10,
    departureTimeOutbound: "10:00",
    arrivalTimeOutbound: "09:20",
    departureAirportOutbound: "ISB",
    arrivalAirportOutbound: "KDU",
    airlineOutbound: "Saudia via PIA",
    flightNumberOutbound: "SV-871 / PK-611",
    departureTimeReturn: "12:00",
    arrivalTimeReturn: "12:00",
    departureAirportReturn: "KDU",
    arrivalAirportReturn: "ISB",
    airlineReturn: "PIA",
    flightNumberReturn: "PK-612",
    durationOutbound: 23 * 60 + 20,
    durationReturn: 0,
    price: 87097,
    selfTransfer: true,
  },
];
export default flightsData;
