import hotelImg from "@/assets/images/hotel1.webp";

const hotelList = [
  {
    id: 1,
    name: "Hotel 1",
    description: "Description 1",
    image: hotelImg,
    review: 2000,
    price: 100,
    location: "Location 1",
    star: 4.4,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Hotel 2",
    description: "Description 2",
    image: hotelImg,
    review: 1500,
    price: 120,
    location: "Location 2",
    star: 5,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Hotel 3",
    description: "Description 3",
    image: hotelImg,
    review: 3000,
    price: 80,
    location: "Location 3",
    star: 3,
    rating: 4.0,
  },
  {
    id: 4,
    name: "Hotel 4",
    description: "Description 4",
    image: hotelImg,
    review: 2500,
    price: 90,
    location: "Location 4",
    star: 4.2,
    rating: 4.3,
  },
  {
    id: 5,
    name: "Hotel 5",
    description: "Description 5",
    image: hotelImg,
    review: 1800,
    price: 110,
    location: "Location 5",
    star: 4.5,
    rating: 4.6,
  },
  {
    id: 6,
    name: "Hotel 6",
    description: "Description 6",
    image: hotelImg,
    review: 2200,
    price: 130,
    location: "Location 6",
    star: 4.7,
    rating: 4.9,
  },
];

export default hotelList;
